
# This file generates R/easySdcTableGauss.R from easySdcTable source files. 

pathR = "C:/R/easySdcTable/R/"

EasyData = readLines(paste0(pathR, "EasyData.R"))
IncProgress = readLines(paste0(pathR, "IncProgress.R"))
PTxyz = readLines(paste0(pathR, "PTxyz.R"))
ReplaceDimList = readLines(paste0(pathR, "ReplaceDimList.R"))
RbindAllwithNames = readLines(paste0(pathR, "RbindAllwithNames.R"))

ProtectTable1 = readLines(paste0(pathR, "ProtectTable1.R"))
ProtectTable = readLines(paste0(pathR, "ProtectTable.R"))


ProtectTable1 = gsub("sdcTable::", "",ProtectTable1)
ProtectTable  = gsub("sdcTable::", "",ProtectTable)

ProtectTable1 = gsub("\\\\link", "",ProtectTable1)
ProtectTable  = gsub("\\\\link", "",ProtectTable)

ProtectTable1 = ProtectTable1[!(grepl("@importFrom", ProtectTable1) & grepl("sdcTable", ProtectTable1))]
ProtectTable = ProtectTable[!(grepl("@importFrom", ProtectTable) & grepl("sdcTable", ProtectTable))]

new_in_ProtectTable <-  
c("  ", "  # START: New in easySdcTableGauss", "  if(tauArgus)", 
  "    method <- '\"tauArgus\"'", "  if(!(method %in% c(\"Gauss\",\"GaussBasic\", \"GaussNoSingleton\"))){", 
  "    warning(paste0('Input method \"', method,'\" ignored. Method set to \"Gauss\".'))", 
  "    tauArgus <- FALSE", "    method = \"Gauss\"", "  }", "  # END: New in easySdcTableGauss ", 
  "  ")


k <- grep("tauArgus <- is.list", ProtectTable)

ProtectTable <- c(ProtectTable[1:k], new_in_ProtectTable, ProtectTable[(k+1):length(ProtectTable)])

REPLACE_sdcTable =
c("", 
  "### @importFrom sdcTable summary getInfo", 
  "### @importFrom sdcTable makeProblem primarySuppression protectTable protect_linked_tables createArgusInput runArgusBatchFile", 
  "", "", 
  "makeProblem <- function(...) {", "  list(...)", "}", 
  "",  
  "primarySuppression <- function(object, ...) object", 
  "", 
  "getInfo <- function(object, ...) object", "", "", 
  "#' @importFrom SSBtools ModelMatrix",
  "protectTable <- function(object, ...) {", 
  "  mm <- ModelMatrix(object$data, hierarchies = object$dimList, crossTable = TRUE)", 
  "  cbind(mm$crossTable, Freq = as.vector(Matrix::crossprod(mm$modelMatrix, object$data[[object$freqVarInd]])), sdcStatus = \"s\")", 
  "}", "", "", 
  "protect_linked_tables <- function(x, y, ...) {", 
  "  list(x = protectTable(x), y = protectTable(y))", "}", 
  "", 
  "createArgusInput <- function(...) \"createArgusInput\"", 
  "runArgusBatchFile <- function(...) \"runArgusBatchFile\""
)


ProtectTable[1] = "#'  Only-Gauss replacement function for easySdcTable::ProtectTable"
ProtectTable1[1] = "#'  Only-Gauss replacement function for easySdcTable::ProtectTable1"

easySdcTableGauss <- 
  c("############################################",
    "#                                          #",
    "#  This file is generated by a r program   #",
    "#  Do not edit by hand                     #",
    "#                                          #",
    "############################################",
    "##### --- EasyData.R ---", "#####################################", EasyData, " ",
    "##### --- IncProgress.R ---", "#####################################", IncProgress, " ",
    "##### --- ProtectTable.R ---", "#####################################", ProtectTable, " ",
    "##### --- ProtectTable1.R ---", "#####################################", ProtectTable1, " ",
    "##### --- PTxyz.R ---", "#####################################", PTxyz, " ",
    "##### --- RbindAllwithNames.R ---", "#####################################", RbindAllwithNames, " ",
    "##### --- REPLACE_sdcTable.R ---", "#####################################", REPLACE_sdcTable, " ",
    "##### --- ReplaceDimList.R ---", "#####################################", ReplaceDimList, " ")

writeLines(easySdcTableGauss,"R/easySdcTableGauss.R")

